/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;

/**
 *
 * @author Rhadryn
 */
public class DuePanel extends javax.swing.JPanel {
    HomeView home;
    private DefaultListModel listModel;

    /**
     * Creates new form HomePanel
     */
    public DuePanel(HomeView home) {
        this.home = home;
        initComponents();
        refreshList();
    }
    
    public void refreshList(){
        listModel = home.getToReview();
        if(listModel.isEmpty()){
            reviewSelectButton.setEnabled(false);
            reviewAllButton.setEnabled(false);
        }
        else{
            reviewList.setModel(listModel);
            reviewAllButton.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        reviewList = new javax.swing.JList<>();
        reviewSelectButton = new javax.swing.JButton();
        reviewAllButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 255, 210));

        reviewList.setBackground(new java.awt.Color(250, 250, 250));
        reviewList.setBorder(new javax.swing.border.MatteBorder(null));
        reviewList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reviewList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reviewListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(reviewList);

        reviewSelectButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reviewSelectButton.setEnabled(false);
        reviewSelectButton.setLabel("Review Selected");
        reviewSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewSelectButtonActionPerformed(evt);
            }
        });

        reviewAllButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reviewAllButton.setEnabled(false);
        reviewAllButton.setLabel("Review All");
        reviewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reviewSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reviewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reviewSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(reviewAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reviewListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reviewListValueChanged
        if(reviewList.getSelectedIndex() < 0){
            reviewSelectButton.setEnabled(false);
        }
        else{
            reviewSelectButton.setEnabled(true);
        }
    }//GEN-LAST:event_reviewListValueChanged

    private void reviewSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewSelectButtonActionPerformed
        home.reviewText(reviewList.getSelectedIndices());
    }//GEN-LAST:event_reviewSelectButtonActionPerformed

    private void reviewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewAllButtonActionPerformed
        home.reviewText();
    }//GEN-LAST:event_reviewAllButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reviewAllButton;
    private javax.swing.JList<String> reviewList;
    private javax.swing.JButton reviewSelectButton;
    // End of variables declaration//GEN-END:variables
}
