/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Words;
import javax.swing.JOptionPane;
import data.Options;

/**
 *
 * @author Rhadryn
 */
public class EditPanel extends javax.swing.JPanel {
    boolean newWords;
    HomeView home;
    Words curWords;

    /**
     * Creates new form EditPanel
     */
    public EditPanel(HomeView home, Words curWords) {
        initComponents();
        this.home = home;
        this.curWords = curWords;
        newWords = curWords.getText().isEmpty();
        if(!newWords){
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabel = new javax.swing.JLabel();
        versionText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        referenceLabel = new javax.swing.JLabel();
        referenceText = new javax.swing.JTextField();
        firstReviewLabel = new javax.swing.JLabel();
        dateResetButton = new javax.swing.JButton();
        textLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(210, 255, 210));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        versionLabel.setFont(Options.getInstance().getParagraphFont());
        versionLabel.setText("Version:");

        versionText.setBackground(new java.awt.Color(250, 250, 250));
        versionText.setFont(Options.getInstance().getParagraphFont());
        versionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                versionTextKeyTyped(evt);
            }
        });

        cancelButton.setFont(Options.getInstance().getButtonFont());
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(Options.getInstance().getButtonFont());
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        referenceLabel.setFont(Options.getInstance().getParagraphFont());
        referenceLabel.setText("Reference:");

        referenceText.setBackground(new java.awt.Color(250, 250, 250));
        referenceText.setFont(Options.getInstance().getParagraphFont());
        referenceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                referenceTextKeyTyped(evt);
            }
        });

        firstReviewLabel.setFont(Options.getInstance().getParagraphFont());
        firstReviewLabel.setText("First review date:");

        dateResetButton.setFont(Options.getInstance().getButtonFont());
        dateResetButton.setText("Reset");
        dateResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateResetButtonActionPerformed(evt);
            }
        });

        textLabel.setFont(Options.getInstance().getParagraphFont());
        textLabel.setText("Text:");

        textArea.setBackground(new java.awt.Color(250, 250, 250));
        textArea.setColumns(20);
        textArea.setFont(Options.getInstance().getParagraphFont());
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstReviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateResetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenceLabel)
                            .addComponent(versionLabel)
                            .addComponent(textLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(versionText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(referenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceLabel)
                    .addComponent(referenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(versionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstReviewLabel)
                    .addComponent(dateResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadData(){
        String indicesText = String.format("%s %s:%s", curWords.getIndices().get(0),
            curWords.getIndices().get(1), curWords.getIndices().get(2));
        referenceText.setText(indicesText);
        //If the verse already has data, we don't want to change the reference
        referenceText.setEditable(false);
        versionText.setText(curWords.getVersion());
        textArea.setText(curWords.getText());
        firstReviewLabel.setText(String.format("First review date:     %tD", 
                curWords.getStartDate()));
    }
    
    private void versionTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_versionTextKeyTyped
        saveButton.setEnabled(true);
    }//GEN-LAST:event_versionTextKeyTyped

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        home.editClose(this);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(referenceText.getText().length() < 1 ||
            textArea.getText().length() < 1){
            JOptionPane.showMessageDialog(this, "Please input text and reference!",
                "Error",JOptionPane.ERROR_MESSAGE);
        }
        int dialogResult = JOptionPane.showConfirmDialog (null,
            "Are you sure you want to save changes?", "Warning",
            JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            curWords.setText(textArea.getText());
            curWords.setVersion(versionText.getText());
            
            //If the word entry is new, add it to the library  
            if(newWords){
                String reference = referenceText.getText();
                reference = reference.replace(":", " ");
                String indices[] = reference.split(" ");
                for(String s : indices){
                    curWords.addIndex(s);
                }
                home.addText(curWords);
            }
        }
        home.editClose(this);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void referenceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_referenceTextKeyTyped
        saveButton.setEnabled(true);
    }//GEN-LAST:event_referenceTextKeyTyped

    private void dateResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateResetButtonActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null,
            "Are you sure you want to reset reviews?", "Warning",
            JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            curWords.setStartDate(null);
            curWords.setLastDate(null);
            curWords.setNextDate(null);
            curWords.setDateIncrement(1);
            loadData();
            saveButton.setEnabled(true);
        }
    }//GEN-LAST:event_dateResetButtonActionPerformed

    private void textAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyTyped
        saveButton.setEnabled(true);
    }//GEN-LAST:event_textAreaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton dateResetButton;
    private javax.swing.JLabel firstReviewLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel referenceLabel;
    private javax.swing.JTextField referenceText;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JTextField versionText;
    // End of variables declaration//GEN-END:variables
}
